"""
Contains classes and functions to write data to files.

Classes
-------
- DocxWriter()

Functions
---------
- write_to_txt()
"""

import getpass
from datetime import datetime
from pathlib import Path
from typing import List

import pytz
from docx import Document
from docx.opc.constants import RELATIONSHIP_TYPE
from docx.opc.exceptions import PackageNotFoundError
from docx.opc.oxml import qn
from docx.oxml import OxmlElement

from notes_converter.utils.constants import TEMPLATE_PATH
from notes_converter.utils.exceptions import NoAvailableTemplate
from notes_converter.utils.structures import Entry


class DocxWriter:
    """
    Represents a Microsoft Word document.

    Attributes
    ----------
    output_path : Path
        The location to save the Word document.
    template_path : Path
        The path to a Word document template. `None`
        means that the default template will be used.

    Methods
    -------
    write_heading():
        Create a heading in the Microsoft Word document.
    write_notes():
        Writes notes to a Microsoft Word document.

    Returns
    -------
    None
        An empty Word document at the given `output_path`.
    """

    def __init__(self, output_path, template_path=None) -> None:
        self.output_path = output_path
        self.template_path = template_path

        self._create_empty_document()

    @property
    def template_path(self):
        return self._template_path

    @template_path.setter
    def template_path(self, path):
        # Is there a custom template path?
        if path:
            template = Path(path)
            valid_template = template.exists() and template.suffix == ".docx"
            if not valid_template:
                self._template_path = TEMPLATE_PATH / "default.docx"
        else:
            self._template_path = TEMPLATE_PATH / "default.docx"

    def _create_empty_document(self):
        """Creates an empty Word document at the location in `self.output_path`."""
        try:
            self._doc = Document(str(self.template_path))
        except PackageNotFoundError:
            # This error is raised only when default.docx is open in another
            # application. Aside from development, that should (in theory)
            # never happen in production.
            raise NoAvailableTemplate

        # Clear existing template data:
        self._doc._body.clear_content()

        # Document title:
        file_name = Path(self.output_path).stem
        self._doc.add_heading(file_name, level=0)

        # Document properties:
        self._doc.core_properties.author = getpass.getuser()
        self._doc.core_properties.comments = "Document generated by NotesConverter."

    def write_heading(self, heading):
        """Creates a heading in the document."""
        self._doc.add_heading(heading, level=1)

    def write_notes(self, notes: List[Entry]):
        """Writes notes to a styled Word document."""

        for note in notes:
            # Note header and date:
            self._doc.add_heading(note.title, level=2)
            self._doc.add_paragraph(_convert_datetime(note.created), style="Date")

            # Note body:
            for index, body in enumerate(note.note_text.split("\n")):
                if index == 0:  # Allow for no text indent on first paragraph.
                    self._doc.add_paragraph(body, style="Head")
                    continue
                self._doc.add_paragraph(body, style="Normal")

            # TODO: an add_run() will be needed to use Word's
            # built-in Hyperlink style. Can add_hyperlink() be
            # modified to use add_run() and to add the hyperlink
            # to that?

            # NOTE: Any note created directly in Annotations in the Gospel Library
            # app or Gospel Library Online will have an "undefined" source
            # location.

            p = self._doc.add_paragraph(style="Link")
            _add_hyperlink(p, note.source_location, note.reference)

        # Save the document only once.
        self._doc.save(str(self.output_path))


# Helper functions


def _convert_datetime(note_time: str) -> str:
    """Converts the time to a human-readable format."""
    default_time = datetime.fromisoformat(note_time.replace("Z", "+00:00"))
    dt = default_time.replace(tzinfo=pytz.utc)
    pacific_tz = pytz.timezone("America/Los_Angeles")
    dt_pacific = dt.astimezone(pacific_tz)
    return dt_pacific.strftime("%B %e, %Y, %I:%M %p %Z").replace("  ", " ")


def _add_hyperlink(paragraph, url, text, color="#0000EE", underline=None):
    """
    Places a hyperlink within a `paragraph` object.

    Parameters
    ----------
    paragraph : The `paragraph` object to which to add the hyperlink.
    url : A string containing a given url.
    text : The text displayed for the url.
    color : The color of the hyperlink.
    underline : Whether an underline is applied.

    Returns
    -------
    A `hyperlink` object with the hyperlink
    """
    # Get access to the document.xml.rels file and get a new relation id value:
    part = paragraph.part
    r_id = part.relate_to(
        url,
        RELATIONSHIP_TYPE.HYPERLINK,
        is_external=True,
    )

    # Create the w:hyperlink tag and add needed values:
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), r_id)

    # Create a w:r element:
    new_run = OxmlElement("w:r")

    # Create a w:rPr element:
    rPr = OxmlElement("w:rPr")

    # Add provided color (if any):
    if color:
        c = OxmlElement("w:color")
        c.set(qn("ct:val"), color)
        rPr.append(c)

    # Remove underline if requested:
    if underline:
        u = OxmlElement("w:u")
        u.set(qn("ct:val"), "single")
        rPr.append(u)
    else:
        u = OxmlElement("w:u")
        u.set(qn("ct:val"), "none")
        rPr.append(u)

    # Join all xml elements and add hyperlink text to w:r element:
    new_run.append(rPr)
    new_run.text = text
    hyperlink.append(new_run)

    paragraph._p.append(hyperlink)

    return hyperlink


# Alternate export formats:


def write_to_txt(notes, output_path, mode="w"):
    """Write the given notes to a `.txt` file with basic formatting."""
    with open(output_path, mode, encoding="utf-8") as f:
        for note in notes:
            f.write("\n\n" + note.title + "\n")
            f.write(_convert_datetime(note.created) + "\n\n")
            for body in note.note_text:
                f.write(body)
            f.write("\n" + note.reference)
